In [17]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import svm

In [18]:
dataset = pd.read_csv('/home/bk/Desktop/mlai/Notes/Day 24/train.csv')
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [19]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Name         889 non-null    object 
 4   Sex          889 non-null    object 
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64  
 7   Parch        889 non-null    int64  
 8   Ticket       889 non-null    object 
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.5+ KB


In [20]:
dataset.drop(['Cabin','Name','Ticket','PassengerId'],axis=1,inplace=True)
le = preprocessing.LabelEncoder()
dataset['Sex'] = le.fit_transform(dataset['Sex'])
dataset['Embarked']=le.fit_transform(dataset['Embarked'])
dataset.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [26]:
cols = dataset.columns.tolist()
cols.remove('Survived')
cols.remove('Age')
cols.remove('Fare')
cols

['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked']

In [27]:
dv, accuracy_scores =[],[]

In [31]:
def svm_for_dv(dependent_col):
    print('DEPENDENT VARIABLE : '+ dependent_col)
    X = dataset.drop([dependent_col],axis=1)
    y=dataset[[dependent_col]]
    X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0,test_size=0.3)
    clf = svm.SVC(gamma=0.01,C=100)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print('Accuracy score: '+str(accuracy_score(y_test,y_pred,normalize=True)))
    print('Confusion Matrix: ')
    print(confusion_matrix(y_test,y_pred))
    print(str(confusion_matrix(y_test,y_pred).trace())+' values are accurately classified out of 267...')
for col in cols:
    print('=======================================================')
    svm_for_dv(col)
    print('=======================================================')

DEPENDENT VARIABLE : Pclass
Accuracy score: 0.9026217228464419
Confusion Matrix: 
[[ 64   4   2]
 [  4  36   9]
 [  1   6 141]]
241 values are accurately classified out of 267...
DEPENDENT VARIABLE : Sex
Accuracy score: 0.7265917602996255
Confusion Matrix: 
[[ 66  32]
 [ 41 128]]
194 values are accurately classified out of 267...
DEPENDENT VARIABLE : SibSp
Accuracy score: 0.7490636704119851
Confusion Matrix: 
[[150  24   7   0   1   0   0]
 [ 21  39   5   0   0   0   0]
 [  4   1   3   0   0   0   0]
 [  0   2   1   3   1   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]
200 values are accurately classified out of 267...
DEPENDENT VARIABLE : Parch
Accuracy score: 0.797752808988764
Confusion Matrix: 
[[187   6   5   0   0   0]
 [ 21  15   3   0   0   1]
 [ 10   6  11   0   0   0]
 [  0   0   1   0   0   0]
 [  1   0   0   0   0   0]
 [  0   0   0   0   0   0]]
213 values are accurately classified out of 267...
DEPENDENT VARIABLE : Emb

/home/bk/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/bk/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/bk/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/bk/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to

In [ ]:
|