# numpy exercises

In [1]:
import numpy as np

 **1. Create a 3x3x3 array with random values**

In [2]:
x = np.random.random((3,3,3))
x

array([[[0.26706604, 0.76983527, 0.57753745],
        [0.64272576, 0.16845781, 0.71545755],
        [0.86547474, 0.40754472, 0.64372228]],

       [[0.08083108, 0.21489985, 0.06574654],
        [0.82968216, 0.88081962, 0.14186702],
        [0.774991  , 0.64083095, 0.18037924]],

       [[0.73230567, 0.3920401 , 0.57987848],
        [0.34930061, 0.51589501, 0.69773403],
        [0.2816408 , 0.82974431, 0.70860516]]])

**2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [3]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**3. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [4]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4. Normalize a 5x5 random matrix**

In [5]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.18931492 0.8189497  0.71315524 0.14367617 0.22469212]
 [0.14149928 0.75438335 0.38272193 1.         0.56702366]
 [0.63634262 0.34034004 0.06682846 0.03063027 0.82037111]
 [0.65269192 0.06225572 0.99518503 0.88249405 0.38580476]
 [0.94944129 0.75681895 0.6159252  0.03657682 0.        ]]


**5. How to find common values between two arrays?**

In [8]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


**6. How to get the dates of yesterday, today and tomorrow?**

In [10]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


**7. Consider two random array A and B, check if they are equal**

In [14]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 1 1 1 0]
Second array:
[0 0 1 1 1 1]
Test above two arrays are equal or not!
False


**8. Create random vector of size 10 and replace the maximum value by 0**

In [16]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.2593011  0.23710663 0.97186384 0.80273863 0.26775289 0.55631022
 0.01373931 0.55457715 0.84243848 0.56023167]
Maximum value replaced by -1:
[0.2593011  0.23710663 0.         0.80273863 0.26775289 0.55631022
 0.01373931 0.55457715 0.84243848 0.56023167]


**9. How to print all the values of an array?**

In [21]:
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**10. Subtract the mean of each row of a matrix**

In [22]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.47260225 0.16061302 0.65255601 0.62735339 0.16789687 0.84002818
  0.34434327 0.43996134 0.58650359 0.01306135]
 [0.25961726 0.7109242  0.738028   0.43629259 0.37284572 0.06891624
  0.49873839 0.38402562 0.48081374 0.75048397]
 [0.73580166 0.66258995 0.96833864 0.02112483 0.54372345 0.56098203
  0.4002775  0.406434   0.76937746 0.65150943]
 [0.99806645 0.38783886 0.17996227 0.07757178 0.56731147 0.43690757
  0.49535061 0.74101857 0.45693016 0.86052803]
 [0.71682997 0.82766086 0.59096976 0.84630744 0.93718527 0.75750968
  0.45450161 0.67697719 0.21873086 0.53003087]]

Subtract the mean of each row of the said matrix:

[[ 0.04211032 -0.26987891  0.22206409  0.19686147 -0.26259505  0.40953625
  -0.08614866  0.00946941  0.15601166 -0.41743058]
 [-0.21045132  0.24085563  0.26795942 -0.03377598 -0.09722285 -0.40115233
   0.02866982 -0.08604295  0.01074517  0.2804154 ]
 [ 0.16378577  0.09057405  0.39632275 -0.55089107 -0.02829245 -0.01103387
  -0.1717384  -0.16558189  0.1

**11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [60]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6 1 8 2 6 9 7 6 9 4 6 1 2 1 2 9 3 1 0 2]
[2. 5. 5. 2. 2. 1. 5. 2. 2. 4.]


**12. How to get the diagonal of a dot product?**

In [44]:
x = np.random.random((3,3))
y = np.random.random((3,3))
z = x.dot(y)
print(z)
print(np.diag(z))

[[0.64498008 1.21297918 0.87955389]
 [0.52591404 0.96504464 0.79145699]
 [0.5001049  0.93162205 0.65272639]]
[0.64498008 0.96504464 0.65272639]


**13. How to find the most frequent value in an array?**

In [26]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[3 6 0 4 4 0 8 2 7 5 0 6 7 1 8 2 3 3 1 2 1 8 1 5 0 9 7 6 6 3 7 8 0 9 8 9 1
 9 6 7]
Most frequent value in the above array:
0


**14. How to get the n largest values of an array**

In [25]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 4
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


**15. How to create a record array from a regular array?**

In [23]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
